image: ubuntu:xenial

types:
  - test
  - tag

test_app:
  type: test
  script: 
    - apt-get update
    - apt-get -y install python-pip libarchive-dev
    - pip install -r requirements.txt
    - python -m unittest discover -s tests.api

semantic_release:
  stage: tag
  image: node:8
  variables:
      GITLAB_TOKEN: $ACCESS_TOKEN
  before_script:
      - npm install -g semantic-release @semantic-release/gitlab-config
      - cat $SEM_RELEASE_OPTIONS > .releaserc.yml
  script:
      - semantic-release -e @semantic-release/gitlab-config
  only:
      - master