image: ubuntu:latest

types:
  - build
  - test

build_app:
  type: build
  script: echo Building!

test_app:
  type: test
  script: 
    - apt-get install python-pip libarchive-dev
    - pip install -r requirements.txt
    - python manage.py test
