image: ubuntu:xenial

types:
  - test

test_app:
  type: test
  script: 
    - apt-get update
    - apt-get -y install python-pip libarchive-dev
    - pip install -r requirements.txt
    - python -m unittest discover -s tests.api
