sudo: true

language: python

python:
  - 2.7

install:
  - sudo apt-get install python-pip libarchive-dev
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

script:
  - cd tests && coverage run --source run_tests.py
after_success:
    coveralls
